# Importing Libraries

In [24]:
%cd ..

c:\Users\lowmi\OneDrive\Desktop\Uni\DSA4262\DSA4262-ACMXZ\data

In [25]:
import pandas as pd
import numpy as np
import os

from preprocessing import (Preprocessing, Modelling)
from utilities import get_percent

# Preparing Data

### Loading parquets

In [3]:
info_data_path = "../data/raw_data/data.info"
with open(info_data_path, 'r') as f:
    info = f.read().splitlines()
data_df = pd.read_parquet("../data/raw_data/data.parquet")

### Reading files and merging dfs

In [4]:
info_list = [info[i].split(",") for i in range(len(info))]
info_df = pd.DataFrame(info_list[1:]) 
info_df.columns = info_list[0]
info_df.to_parquet("info.parquet")

In [5]:
df = data_df.merge(info_df, how = "left", left_on = ["transcript", "position"], 
                    right_on = ["transcript_id", "transcript_position"])

In [6]:
# df_1 = pd.DataFrame(data_1.groupby(['transcript', 'position', 'nucleotides', 'label'], as_index=False)
#                             .agg({'dwelling_time': [get_percent(25), get_percent(50), get_percent(75), np.mean], 
#                                     'std': [get_percent(25), get_percent(50), get_percent(75), np.mean], 
#                                     'mean': [get_percent(25), get_percent(50), get_percent(75), np.mean]}))

# Preprocessing

id_cols = ['transcript', 'position']
<br>
label encoding = ['nucleotides']
<br>
normalization = ['dwelling_time', 'std', 'mean']

In [7]:
df_pre = Preprocessing(df)

In [8]:
df_pre.model_features_and_clean()

,transcript,position,nucleotides,gene_id,dwelling_time,std,mean,label
185,ENST00000000233,244,AGACC,ENSG00000004059,0.01770,10.40,122.0,0
186,ENST00000000233,244,AGACC,ENSG00000004059,0.00844,4.67,126.0,0
187,ENST00000000233,244,AGACC,ENSG00000004059,0.01360,12.00,124.0,0
188,ENST00000000233,244,AGACC,ENSG00000004059,0.00830,5.01,130.0,0
189,ENST00000000233,244,AGACC,ENSG00000004059,0.00266,3.94,129.0,0
...,...,...,...,...,...,...,...,...
33081261,ENST00000641834,1693,TGACA,ENSG00000167747,0.00564,10.20,116.0,0
33081262,ENST00000641834,1693,TGACA,ENSG00000167747,0.00598,12.30,110.0,0
33081263,ENST00000641834,1693,TGACA,ENSG00000167747,0.00398,6.58,113.0,0
33081264,ENST00000641834,1693,TGACA,ENSG00000167747,0.00913,10.40,108.0,0
33081265,ENST00000641834,1693,TGACA,ENSG00000167747,0.00303,9.98,118.0,0

In [9]:
df_pre.feature_eng()

,gene_id,transcript,position,nucleotides,label,dwelling_time_25,dwelling_time_50,dwelling_time_75,dwelling_time_mean,std_25,std_50,std_75,std_mean,mean_25,mean_50,mean_75,mean_mean
0,ENSG00000000003,ENST00000373020,1006,AGACC,0,0.005980,0.009090,0.014900,0.011677,4.3000,5.600,7.5800,6.000000,125.00,127.00,128.00,127.000000
1,ENSG00000000003,ENST00000373020,1013,AAACT,0,0.003320,0.005305,0.007763,0.006050,3.8850,4.415,4.8200,4.091500,100.00,102.00,105.00,102.675000
2,ENSG00000000003,ENST00000373020,1149,AAACA,0,0.004958,0.006885,0.010733,0.008051,1.9875,2.570,2.9875,2.652227,96.80,98.50,100.75,99.081818
3,ENSG00000000003,ENST00000373020,512,TAACT,0,0.003980,0.007735,0.013375,0.011177,2.0800,2.375,2.7300,2.496500,97.05,98.05,99.05,97.965000
4,ENSG00000000003,ENST00000373020,689,AAACA,0,0.003650,0.006420,0.008960,0.007332,1.9600,2.430,2.9100,2.551905,96.20,98.70,99.70,97.928571
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121833,ENSG00000284707,ENST00000641784,3122,TGACC,1,0.004432,0.007165,0.009483,0.007801,4.3575,6.365,8.4275,6.736167,116.00,117.00,120.25,118.050000
121834,ENSG00000284707,ENST00000641784,3142,TGACC,0,0.004320,0.006100,0.009630,0.007614,6.9200,8.880,10.6000,8.877377,116.00,120.00,123.00,119.721311
121835,ENSG00000284707,ENST00000641784,3224,GGACT,1,0.004882,0.006310,0.011525,0.008247,3.0200,4.420,5.6125,4.507167,122.00,125.00,127.25,124.466667
121836,ENSG00000284707,ENST00000641784,3243,GAACA,0,0.005145,0.006580,0.009157,0.007648,2.2575,2.675,3.1225,2.998125,95.35,97.60,98.85,97.346875
121837,ENSG00000284707,ENST00000641784,3266,TAACT,0,0.004432,0.005785,0.007955,0.006831,1.8825,2.170,2.4625,2.194032,98.90,99.75,101.00,99.730645

In [10]:
df_all_features = df_pre.df

In [11]:
df_train, df_test, df_val, X_train, y_train, X_val, y_val, X_test, y_test, df_val_id, list_train = df_pre.split_stratified_into_train_val_test(random_state=42)

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

train target percentage: 0.049255441008018326
test target percentage: 0.06377880184331797
val target percentage: 0.07129746472410232
train data shape: (107379, 14)
validation data shape: (17434, 14)
test data shape: (16275, 14)

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [12]:
df_pre.X_train

,nucleotides,dwelling_time_25,dwelling_time_50,dwelling_time_75,dwelling_time_mean,std_25,std_50,std_75,std_mean,mean_25,mean_50,mean_75,mean_mean
0,AGACC,0.005980,0.009090,0.014900,0.011677,4.3000,5.600,7.5800,6.000000,125.00,127.00,128.00,127.000000
1,AAACT,0.003320,0.005305,0.007763,0.006050,3.8850,4.415,4.8200,4.091500,100.00,102.00,105.00,102.675000
2,AAACA,0.004958,0.006885,0.010733,0.008051,1.9875,2.570,2.9875,2.652227,96.80,98.50,100.75,99.081818
3,TAACT,0.003980,0.007735,0.013375,0.011177,2.0800,2.375,2.7300,2.496500,97.05,98.05,99.05,97.965000
4,AAACA,0.003650,0.006420,0.008960,0.007332,1.9600,2.430,2.9100,2.551905,96.20,98.70,99.70,97.928571
...,...,...,...,...,...,...,...,...,...,...,...,...,...
107374,TGACC,0.004432,0.007165,0.009483,0.007801,4.3575,6.365,8.4275,6.736167,116.00,117.00,120.25,118.050000
107375,TGACC,0.004320,0.006100,0.009630,0.007614,6.9200,8.880,10.6000,8.877377,116.00,120.00,123.00,119.721311
107376,GGACT,0.004882,0.006310,0.011525,0.008247,3.0200,4.420,5.6125,4.507167,122.00,125.00,127.25,124.466667
107377,GAACA,0.005145,0.006580,0.009157,0.007648,2.2575,2.675,3.1225,2.998125,95.35,97.60,98.85,97.346875
107378,TAACT,0.004432,0.005785,0.007955,0.006831,1.8825,2.170,2.4625,2.194032,98.90,99.75,101.00,99.730645

In [13]:
X_train_oversampled = df_pre.oversample_undersample()

In [14]:
X_train_oversampled

,nucleotides,dwelling_time_25,dwelling_time_50,dwelling_time_75,dwelling_time_mean,std_25,std_50,std_75,std_mean,mean_25,mean_50,mean_75,mean_mean
0,GGACT,0.006310,0.009230,0.013300,0.010990,4.800000,6.160000,8.280000,6.639487,118.000000,120.000000,122.000000,119.555556
1,GAACA,0.004298,0.006310,0.009673,0.007737,2.687500,3.375000,4.952500,4.138917,91.100000,93.100000,95.225000,93.633333
2,AAACT,0.004092,0.006475,0.009960,0.007692,2.447500,3.015000,3.842500,3.269531,102.000000,105.000000,107.000000,104.375000
3,GAACT,0.003910,0.005980,0.009630,0.007635,2.990000,3.480000,4.290000,4.013333,98.100000,99.600000,101.500000,100.089308
4,AAACA,0.004650,0.005640,0.006805,0.006277,2.430000,2.920000,3.425000,3.024444,94.800000,96.300000,98.000000,96.637037
...,...,...,...,...,...,...,...,...,...,...,...,...,...
51562,GAACA,0.004125,0.005921,0.009163,0.007203,2.437136,2.841286,3.526068,3.191178,93.865048,94.977913,96.444175,95.211601
51563,GGACT,0.004852,0.007296,0.010985,0.008554,4.339364,6.179448,8.604927,6.646295,120.996059,123.000000,124.984234,122.610429
51564,TGACA,0.004046,0.005856,0.008492,0.006910,5.227768,6.854815,8.788404,7.095782,115.000000,117.000000,121.000000,117.901847
51565,GAACT,0.004046,0.005340,0.007102,0.005812,2.503244,2.953576,3.821851,3.372486,98.592722,100.000000,102.000000,100.442201
51566,GGACA,0.004052,0.007667,0.011640,0.009199,4.449837,5.999572,7.460480,6.296453,110.281919,115.000000,119.718081,115.004690

In [15]:
X_train_oversampled

,nucleotides,dwelling_time_25,dwelling_time_50,dwelling_time_75,dwelling_time_mean,std_25,std_50,std_75,std_mean,mean_25,mean_50,mean_75,mean_mean
0,GGACT,0.006310,0.009230,0.013300,0.010990,4.800000,6.160000,8.280000,6.639487,118.000000,120.000000,122.000000,119.555556
1,GAACA,0.004298,0.006310,0.009673,0.007737,2.687500,3.375000,4.952500,4.138917,91.100000,93.100000,95.225000,93.633333
2,AAACT,0.004092,0.006475,0.009960,0.007692,2.447500,3.015000,3.842500,3.269531,102.000000,105.000000,107.000000,104.375000
3,GAACT,0.003910,0.005980,0.009630,0.007635,2.990000,3.480000,4.290000,4.013333,98.100000,99.600000,101.500000,100.089308
4,AAACA,0.004650,0.005640,0.006805,0.006277,2.430000,2.920000,3.425000,3.024444,94.800000,96.300000,98.000000,96.637037
...,...,...,...,...,...,...,...,...,...,...,...,...,...
51562,GAACA,0.004125,0.005921,0.009163,0.007203,2.437136,2.841286,3.526068,3.191178,93.865048,94.977913,96.444175,95.211601
51563,GGACT,0.004852,0.007296,0.010985,0.008554,4.339364,6.179448,8.604927,6.646295,120.996059,123.000000,124.984234,122.610429
51564,TGACA,0.004046,0.005856,0.008492,0.006910,5.227768,6.854815,8.788404,7.095782,115.000000,117.000000,121.000000,117.901847
51565,GAACT,0.004046,0.005340,0.007102,0.005812,2.503244,2.953576,3.821851,3.372486,98.592722,100.000000,102.000000,100.442201
51566,GGACA,0.004052,0.007667,0.011640,0.009199,4.449837,5.999572,7.460480,6.296453,110.281919,115.000000,119.718081,115.004690

In [16]:
X_train_enc, pipe = df_pre.encoding_train()

columns after preprocessing : ['dwelling_time_25', 'dwelling_time_50', 'dwelling_time_75', 'dwelling_time_mean', 'std_25', 'std_50', 'std_75', 'std_mean', 'mean_25', 'mean_50', 'mean_75', 'mean_mean', 'nucleotides']

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [17]:
X_test_enc = df_pre.encoding_test_val()

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [18]:
X_val_enc = df_pre.encoding_test_val(test = False)

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [23]:
X_train_25 = X_train_enc.drop(columns=['dwelling_time_50', 'dwelling_time_75', 'dwelling_time_mean', 'std_50', 'std_75', 'std_mean', 'mean_50', 'mean_75', 'mean_mean'])
X_train_50 = X_train_enc.drop(columns=['dwelling_time_25', 'dwelling_time_75', 'dwelling_time_mean', 'std_25', 'std_75', 'std_mean', 'mean_25', 'mean_75', 'mean_mean'])
X_train_75 = X_train_enc.drop(columns=['dwelling_time_50', 'dwelling_time_25', 'dwelling_time_mean', 'std_50', 'std_25', 'std_mean', 'mean_50', 'mean_25', 'mean_mean'])
X_train_mean = X_train_enc.drop(columns=['dwelling_time_50', 'dwelling_time_75', 'dwelling_time_25', 'std_50', 'std_75', 'std_25', 'mean_50', 'mean_75', 'mean_25'])

,dwelling_time_75,std_75,mean_75,position_0_A,position_0_C,position_0_G,position_0_T,position_1_A,position_1_C,position_1_G,...,position_2_G,position_2_T,position_3_A,position_3_C,position_3_G,position_3_T,position_4_A,position_4_C,position_4_G,position_4_T
0,0.452857,0.479151,0.657258,0,0,1,0,0,0,1,...,0,0,0,1,0,0,0,0,0,1
1,0.268228,0.235735,0.11744,0,0,1,0,1,0,0,...,0,0,0,1,0,0,1,0,0,0
2,0.28286,0.154535,0.354839,1,0,0,0,1,0,0,...,0,0,0,1,0,0,0,0,0,1
3,0.266064,0.187271,0.243952,0,0,1,0,1,0,0,...,0,0,0,1,0,0,0,0,0,1
4,0.12228,0.123994,0.173387,1,0,0,0,1,0,0,...,0,0,0,1,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51562,0.24232,0.131388,0.14202,0,0,1,0,1,0,0,...,0,0,0,1,0,0,1,0,0,0
51563,0.335027,0.502921,0.717424,0,0,1,0,0,0,1,...,0,0,0,1,0,0,0,0,0,1
51564,0.208146,0.516343,0.637097,0,0,0,1,0,0,1,...,0,0,0,1,0,0,1,0,0,0
51565,0.137388,0.153025,0.254032,0,0,1,0,1,0,0,...,0,0,0,1,0,0,0,0,0,1
51566,0.368383,0.419201,0.611252,0,0,1,0,0,0,1,...,0,0,0,1,0,0,1,0,0,0

# Exporting Datasets

In [26]:
%cd ../data/preprocessed_data

c:\Users\lowmi\OneDrive\Desktop\Uni\DSA4262\DSA4262-ACMXZ\data\preprocessed_data

In [27]:
df_all_features.to_parquet("df_all_features.parquet") # df containing all features, before splitting/encoding
df_pre.df_train.to_parquet("df_train.parquet") # df containing all features, after splitting, before encoding
df_pre.df_test.to_parquet("df_test.parquet") # df containing all features, after splitting, before encoding
df_pre.df_val.to_parquet("df_val.parquet") # df containing all features, after splitting, before encoding
df_pre.X_train.to_parquet("X_train.parquet") # df containing all features, after splitting, before encoding
df_pre.y_train.to_parquet("y_train.parquet") # df containing all features, after splitting, before encoding
df_pre.X_val.to_parquet("X_val.parquet") # df containing all features, after splitting, before encoding
df_pre.y_val.to_parquet("y_val.parquet") # df containing all features, after splitting, before encoding
df_pre.X_test.to_parquet("X_test.parquet") # df containing all features, after splitting, before encoding
df_pre.y_test.to_parquet("y_test.parquet") # df containing all features, after splitting, before encoding
df_val_id.to_parquet("df_val_id.parquet") # df containing all features, after splitting, before encoding
df_pre.X_train_enc.to_parquet("X_train_enc.parquet") # df containing all features, after encoding and oversampling
df_pre.X_test_enc.to_parquet("X_test_enc.parquet") # df containing all features, after encoding and oversampling
df_pre.X_val_enc.to_parquet("X_val_enc.parquet") # df containing all features, after encoding and oversampling
X_train_25.to_parquet("X_train_25.parquet")  # final df containing 25 percentile features for modelling
X_train_50.to_parquet("X_train_50.parquet") # final df containing 50 percentile features for modelling
X_train_75.to_parquet("X_train_75.parquet") # final df containing 75 percentile features for modelling
X_train_mean.to_parquet("X_train_mean.parquet") # final df containing mean features for modelling