# Importing Libraries

In [1]:
%cd ../..

c:\Users\lowmi\OneDrive\Desktop\Uni\DSA4262\DSA4262-ACMXZ

In [2]:
import pandas as pd
import numpy as np
import os

from util.preprocess import (Preprocessing)
from util.model import (get_percent, Modelling)

# Preparing Data

### Loading parquets

In [3]:
data_1 = pd.read_parquet("data/merged_data/merged_data_v2_1.parquet")
data_2 = pd.read_parquet("data/merged_data/merged_data_v2_2.parquet")
data_3 = pd.read_parquet("data/merged_data/merged_data_v2_3.parquet")
df = pd.concat([data_1, data_2, data_3])

### Reading files and merging dfs

In [4]:
# df_1 = pd.DataFrame(data_1.groupby(['transcript', 'position', 'nucleotides', 'label'], as_index=False)
#                             .agg({'dwelling_time': [get_percent(25), get_percent(50), get_percent(75), np.mean], 
#                                     'std': [get_percent(25), get_percent(50), get_percent(75), np.mean], 
#                                     'mean': [get_percent(25), get_percent(50), get_percent(75), np.mean]}))

# Preprocessing

id_cols = ['transcript', 'position']
<br>
label encoding = ['nucleotides']
<br>
normalization = ['dwelling_time', 'std', 'mean']

In [5]:
df_pre = Preprocessing(df)

In [6]:
df_pre.model_features_and_clean()

,transcript,position,nucleotides,reads_count,gene_id,dwellingtime_-1,std_-1,mean_-1,dwellingtime_0,std_0,mean_0,dwellingtime_+1,std_+1,mean_+1,label
0,ENST00000000233,244,AAGACCA,185,ENSG00000004059,0.00299,2.06,125.0,0.01770,10.40,122.0,0.00930,10.90,84.1,0
1,ENST00000000233,244,AAGACCA,185,ENSG00000004059,0.00631,2.53,125.0,0.00844,4.67,126.0,0.01030,6.30,80.9,0
2,ENST00000000233,244,AAGACCA,185,ENSG00000004059,0.00465,3.92,109.0,0.01360,12.00,124.0,0.00498,2.13,79.6,0
3,ENST00000000233,244,AAGACCA,185,ENSG00000004059,0.00398,2.06,125.0,0.00830,5.01,130.0,0.00498,3.78,80.4,0
4,ENST00000000233,244,AAGACCA,185,ENSG00000004059,0.00664,2.92,120.0,0.00266,3.94,129.0,0.01300,7.15,82.2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11027101,ENST00000641834,1693,TTGACAT,52,ENSG00000167747,0.00418,7.49,108.0,0.00564,10.20,116.0,0.01000,2.01,76.4,0
11027102,ENST00000641834,1693,TTGACAT,52,ENSG00000167747,0.00664,1.91,109.0,0.00598,12.30,110.0,0.01760,2.61,74.6,0
11027103,ENST00000641834,1693,TTGACAT,52,ENSG00000167747,0.00721,4.58,105.0,0.00398,6.58,113.0,0.00316,2.28,85.3,0
11027104,ENST00000641834,1693,TTGACAT,52,ENSG00000167747,0.00266,2.33,109.0,0.00913,10.40,108.0,0.00664,4.44,76.8,0
11027105,ENST00000641834,1693,TTGACAT,52,ENSG00000167747,0.00564,3.13,110.0,0.00303,9.98,118.0,0.01930,1.79,76.2,0

In [7]:
df_pre.feature_eng()

In [ ]:
df_all_features = df_pre.df

In [ ]:
df_train, df_test, df_val, X_train, y_train, X_val, y_val, X_test, y_test, df_val_id, list_train = df_pre.split_stratified_into_train_val_test(random_state=42)

train target percentage: 0.043292122202922244
test target percentage: 0.0506553911205074
val target percentage: 0.052622910318702136
train data shape: (97870, 42)
validation data shape: (12143, 42)
test data shape: (11825, 42)

In [ ]:
df_pre.X_train

,nucleotides,reads_count,dwelling_time_-1_25,dwelling_time_-1_50,dwelling_time_-1_75,dwelling_time_-1_mean,std_-1_25,std_-1_50,std_-1_75,std_-1_mean,...,dwelling_time_+1_75,dwelling_time_+1_mean,std_+1_25,std_+1_50,std_+1_75,std_+1_mean,mean_+1_25,mean_+1_50,mean_+1_75,mean_+1_mean
0,TAGACCT,21,0.007650,0.009760,0.015100,0.010726,2.8900,3.100,3.3400,3.021905,...,0.008300,0.006490,2.0600,3.210,5.1700,3.900476,75.800,77.10,77.800,76.857143
1,AAAACTA,20,0.007965,0.009800,0.013175,0.011538,2.1925,2.460,2.7325,2.471500,...,0.011600,0.010213,2.4775,2.870,4.0100,3.299000,92.125,93.25,94.975,93.765000
2,GAAACAC,22,0.004917,0.007155,0.009473,0.008890,2.2100,3.030,4.2975,3.440909,...,0.007832,0.006491,1.6300,1.855,2.2675,2.028182,89.450,90.65,92.600,90.777273
3,ATAACTC,20,0.004040,0.005990,0.008387,0.007247,1.7400,2.325,2.7050,2.359500,...,0.011200,0.008500,1.3900,1.570,1.8750,1.588750,92.100,92.55,93.325,92.330000
4,TAAACAA,21,0.005310,0.007640,0.014300,0.009868,1.7500,1.980,2.2300,1.972857,...,0.008590,0.006917,1.7400,2.190,2.3700,2.198571,88.500,89.60,90.600,89.385714
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97865,CTGACCC,60,0.003980,0.005475,0.007947,0.007506,2.9425,3.270,4.2250,3.685833,...,0.008677,0.006870,1.9425,2.525,3.4000,2.844667,79.675,81.15,82.725,80.915000
97866,CTGACCC,61,0.005520,0.007640,0.011000,0.008712,2.9700,3.470,3.8400,3.650164,...,0.006970,0.005795,2.2900,3.040,3.7100,3.218689,76.500,78.00,79.500,77.859016
97867,GGGACTG,60,0.004650,0.006970,0.011150,0.008452,2.9300,3.700,4.7675,3.807667,...,0.007640,0.006606,2.3125,3.045,4.3775,3.443833,88.675,91.45,93.325,91.126667
97868,GGAACAA,64,0.004877,0.007350,0.010325,0.008700,6.2825,7.680,9.1225,7.686719,...,0.006302,0.005190,1.6900,2.130,2.5300,2.203750,86.750,88.70,90.500,88.439063
97869,CTAACTT,62,0.004000,0.005065,0.006970,0.005972,1.4625,1.760,2.1875,1.874516,...,0.008438,0.006503,1.6100,1.825,2.2200,1.977742,91.550,92.65,93.200,92.453226

In [ ]:
X_train_oversampled, y_train = df_pre.oversample_undersample()

In [ ]:
X_train_enc, pipe = df_pre.encoding_train()

columns after preprocessing : ['reads_count', 'dwelling_time_-1_25', 'dwelling_time_-1_50', 'dwelling_time_-1_75', 'dwelling_time_-1_mean', 'std_-1_25', 'std_-1_50', 'std_-1_75', 'std_-1_mean', 'mean_-1_25', 'mean_-1_50', 'mean_-1_75', 'mean_-1_mean', 'dwelling_time_0_25', 'dwelling_time_0_50', 'dwelling_time_0_75', 'dwelling_time_0_mean', 'std_0_25', 'std_0_50', 'std_0_75', 'std_0_mean', 'mean_0_25', 'mean_0_50', 'mean_0_75', 'mean_0_mean', 'dwelling_time_+1_25', 'dwelling_time_+1_50', 'dwelling_time_+1_75', 'dwelling_time_+1_mean', 'std_+1_25', 'std_+1_50', 'std_+1_75', 'std_+1_mean', 'mean_+1_25', 'mean_+1_50', 'mean_+1_75', 'mean_+1_mean', 'nucleotides']

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
X_test_enc = df_pre.encoding_test_val()

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
X_val_enc = df_pre.encoding_test_val(test = False)

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
X_train_25 = X_train_enc.drop(columns=['dwelling_time_-1_50', 'dwelling_time_-1_75', 'dwelling_time_-1_mean', 'std_-1_50', 'std_-1_75', 'std_-1_mean', 'mean_-1_50', 'mean_-1_75', 'mean_-1_mean',
                                        'dwelling_time_0_50', 'dwelling_time_0_75', 'dwelling_time_0_mean', 'std_0_50', 'std_0_75', 'std_0_mean', 'mean_0_50', 'mean_0_75', 'mean_0_mean',
                                        'dwelling_time_+1_50', 'dwelling_time_+1_75', 'dwelling_time_+1_mean', 'std_+1_50', 'std_+1_75', 'std_+1_mean', 'mean_+1_50', 'mean_+1_75', 'mean_+1_mean'])

X_train_50 = X_train_enc.drop(columns=['dwelling_time_-1_25', 'dwelling_time_-1_75', 'dwelling_time_-1_mean', 'std_-1_25', 'std_-1_75', 'std_-1_mean', 'mean_-1_25', 'mean_-1_75', 'mean_-1_mean',
                                        'dwelling_time_0_25', 'dwelling_time_0_75', 'dwelling_time_0_mean', 'std_0_25', 'std_0_75', 'std_0_mean', 'mean_0_25', 'mean_0_75', 'mean_0_mean',
                                        'dwelling_time_+1_25', 'dwelling_time_+1_75', 'dwelling_time_+1_mean', 'std_+1_25', 'std_+1_75', 'std_+1_mean', 'mean_+1_25', 'mean_+1_75', 'mean_+1_mean'])

X_train_75 = X_train_enc.drop(columns=['dwelling_time_-1_25', 'dwelling_time_-1_50', 'dwelling_time_-1_mean', 'std_-1_25', 'std_-1_50', 'std_-1_mean', 'mean_-1_25', 'mean_-1_50', 'mean_-1_mean',
                                        'dwelling_time_0_25', 'dwelling_time_0_50', 'dwelling_time_0_mean', 'std_0_25', 'std_0_50', 'std_0_mean', 'mean_0_25', 'mean_0_50', 'mean_0_mean',
                                        'dwelling_time_+1_25', 'dwelling_time_+1_50', 'dwelling_time_+1_mean', 'std_+1_25', 'std_+1_50', 'std_+1_mean', 'mean_+1_25', 'mean_+1_50', 'mean_+1_mean'])

X_train_mean = X_train_enc.drop(columns=['dwelling_time_-1_25', 'dwelling_time_-1_50', 'dwelling_time_-1_75', 'std_-1_25', 'std_-1_50', 'std_-1_75', 'mean_-1_25', 'mean_-1_50', 'mean_-1_75',
                                        'dwelling_time_0_25', 'dwelling_time_0_50', 'dwelling_time_0_75', 'std_0_25', 'std_0_50', 'std_0_75', 'mean_0_25', 'mean_0_50', 'mean_0_75',
                                        'dwelling_time_+1_25', 'dwelling_time_+1_50', 'dwelling_time_+1_75', 'std_+1_25', 'std_+1_50', 'std_+1_75', 'mean_+1_25', 'mean_+1_50', 'mean_+1_75'])

In [ ]:
X_train_25

,reads_count,dwelling_time_-1_25,std_-1_25,mean_-1_25,dwelling_time_0_25,std_0_25,mean_0_25,dwelling_time_+1_25,std_+1_25,mean_+1_25,...,position_4_G,position_4_T,position_5_A,position_5_C,position_5_G,position_5_T,position_6_A,position_6_C,position_6_G,position_6_T
0,0.012435,0.232362,0.151012,0.480287,0.112903,0.177553,0.178536,0.242053,0.087376,0.522642,...,0,0,0,1,0,0,0,0,0,1
1,0.023834,0.167178,0.098988,0.713262,0.197793,0.35004,0.653962,0.170199,0.137391,0.254717,...,0,0,0,1,0,0,0,0,0,1
2,0.003109,0.055215,0.066929,0.159498,0.169779,0.076513,0.131394,0.280795,0.090389,0.571698,...,0,0,1,0,0,0,1,0,0,0
3,0.025907,0.224949,0.187852,0.498208,0.123939,0.503599,0.653962,0.205298,0.083158,0.441509,...,0,0,1,0,0,0,0,0,0,1
4,0.003109,0.072086,0.04387,0.340502,0.223684,0.08611,0.42327,0.286755,0.112082,0.884906,...,0,0,0,0,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30401,0.110881,0.225156,0.122215,0.659498,0.193412,0.234138,0.573721,0.303117,0.07495,0.583849,...,0,0,0,0,0,1,0,1,0,0
30402,0.004145,0.504763,0.413137,0.646189,0.227592,0.245546,0.563544,0.225406,0.165832,0.120639,...,0,0,0,1,0,0,0,1,0,0
30403,0.012435,0.153629,0.126798,0.68923,0.201763,0.273326,0.616394,0.463237,0.143124,0.679518,...,0,0,0,0,0,1,0,0,1,0
30404,0.07772,0.191088,0.706278,0.820789,0.070829,0.186463,0.107541,0.317701,0.116583,0.499288,...,0,0,0,1,0,0,0,1,0,0
30405,0.023834,0.377773,0.331188,0.641577,0.239672,0.394966,0.623127,0.142164,0.201444,0.300978,...,0,0,1,0,0,0,0,1,0,0

# Exporting Datasets

In [ ]:
%cd data/new_preprocessed_data

c:\Users\lowmi\OneDrive\Desktop\Uni\DSA4262\DSA4262-ACMXZ\data\new_preprocessed_data

In [ ]:
#into archive
df_all_features.to_parquet("archive/df_all_features.parquet") # df containing all features, before splitting/encoding
df_pre.df_test.to_parquet("archive/df_test.parquet") # df test containing all features and target, after splitting, before encoding
df_pre.df_train.to_parquet("archive/df_train.parquet") # df trin containing all features and target, after splitting, before encoding
df_val_id.to_parquet("archive/df_val_id.parquet") # df val containing all features, identity cols and target, after splitting, before encoding
df_pre.df_val.to_parquet("archive/df_val.parquet") # df val containing all features and target, after splitting, before encoding
df_pre.X_test.to_parquet("archive/X_test.parquet") # df test containing all features, after splitting, before encoding
df_pre.X_train.to_parquet("archive/X_train.parquet") # df train containing all features, after splitting, before encoding
df_pre.X_val.to_parquet("archive/X_val.parquet") # df val containing all features, after splitting, before encoding

#into test
df_pre.X_test_enc.to_parquet("test/X_test_enc.parquet") # df test containing all features, after encoding and oversampling
df_pre.y_test.to_parquet("test/y_test.parquet") # target test, after splitting, before encoding

#into training
X_train_25.to_parquet("training/X_train_25.parquet")  # final df containing 25 percentile features for modelling
X_train_50.to_parquet("training/X_train_50.parquet") # final df containing 50 percentile features for modelling
X_train_75.to_parquet("training/X_train_75.parquet") # final df containing 75 percentile features for modelling
df_pre.X_train_enc.to_parquet("training/X_train_enc.parquet") # df train containing all features, after encoding and oversampling
X_train_mean.to_parquet("training/X_train_mean.parquet") # final df containing mean features for modelling
df_pre.y_train.to_parquet("training/y_train.parquet") # target train, after splitting, before encoding

#into validation
df_pre.X_val_enc.to_parquet("validation/X_val_enc.parquet") # df val containing all features, after encoding and oversampling
df_pre.y_val.to_parquet("validation/y_val.parquet") # target val, after splitting, before encoding

In [27]:
df_all_features.to_parquet("df_all_features.parquet") # df containing all features, before splitting/encoding
df_pre.df_train.to_parquet("df_train.parquet") # df trin containing all features and target, after splitting, before encoding
df_pre.df_test.to_parquet("df_test.parquet") # df test containing all features and target, after splitting, before encoding
df_pre.df_val.to_parquet("df_val.parquet") # df val containing all features and target, after splitting, before encoding
df_pre.X_train.to_parquet("X_train.parquet") # df train containing all features, after splitting, before encoding
df_pre.y_train.to_parquet("y_train.parquet") # target train, after splitting, before encoding
df_pre.X_val.to_parquet("X_val.parquet") # df val containing all features, after splitting, before encoding
df_pre.y_val.to_parquet("y_val.parquet") # target val, after splitting, before encoding
df_pre.X_test.to_parquet("X_test.parquet") # df test containing all features, after splitting, before encoding
df_pre.y_test.to_parquet("y_test.parquet") # target test, after splitting, before encoding
df_val_id.to_parquet("df_val_id.parquet") # df val containing all features, identity cols and target, after splitting, before encoding
df_pre.X_train_enc.to_parquet("X_train_enc.parquet") # df train containing all features, after encoding and oversampling
df_pre.X_test_enc.to_parquet("X_test_enc.parquet") # df test containing all features, after encoding and oversampling
df_pre.X_val_enc.to_parquet("X_val_enc.parquet") # df val containing all features, after encoding and oversampling
X_train_25.to_parquet("X_train_25.parquet")  # final df containing 25 percentile features for modelling
X_train_50.to_parquet("X_train_50.parquet") # final df containing 50 percentile features for modelling
X_train_75.to_parquet("X_train_75.parquet") # final df containing 75 percentile features for modelling
X_train_mean.to_parquet("X_train_mean.parquet") # final df containing mean features for modelling

In [29]:
df_pre.y_train

      label
0         0
1         0
2         0
3         0
4         0
...     ...
51562     1
51563     1
51564     1
51565     1
51566     1

[51567 rows x 1 columns]