# Importing Libraries

In [1]:
%cd ../..

c:\Users\lowmi\OneDrive\Desktop\Uni\DSA4262\DSA4262-ACMXZ

In [2]:
import pandas as pd
import numpy as np
import os
import pickle

from util.preprocess import (Preprocessing)
from util.model import (get_percent, Modelling)

c:\Users\lowmi\anaconda3\envs\DSA4262\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

# Preparing Data

### Loading parquets

In [3]:
data_1 = pd.read_parquet("data/merged_data/merged_data_v2_1.parquet")
data_2 = pd.read_parquet("data/merged_data/merged_data_v2_2.parquet")
data_3 = pd.read_parquet("data/merged_data/merged_data_v2_3.parquet")
df = pd.concat([data_1, data_2, data_3])

### Reading files and merging dfs

In [1]:
# df_1 = pd.DataFrame(data_1.groupby(['transcript', 'position', 'nucleotides', 'label'], as_index=False)
#                             .agg({'dwelling_time': [get_percent(25), get_percent(50), get_percent(75), np.mean], 
#                                     'std': [get_percent(25), get_percent(50), get_percent(75), np.mean], 
#                                     'mean': [get_percent(25), get_percent(50), get_percent(75), np.mean]}))

# Preprocessing

id_cols = ['transcript', 'position']
<br>
label encoding = ['nucleotides']
<br>
normalization = ['dwelling_time', 'std', 'mean']

In [4]:
df_pre = Preprocessing(df)

In [5]:
df_pre.model_features_and_clean()

,transcript,position,nucleotides,reads_count,gene_id,dwellingtime_-1,std_-1,mean_-1,dwellingtime_0,std_0,mean_0,dwellingtime_+1,std_+1,mean_+1,label
0,ENST00000000233,244,AAGACCA,185,ENSG00000004059,0.00299,2.06,125.0,0.01770,10.40,122.0,0.00930,10.90,84.1,0
1,ENST00000000233,244,AAGACCA,185,ENSG00000004059,0.00631,2.53,125.0,0.00844,4.67,126.0,0.01030,6.30,80.9,0
2,ENST00000000233,244,AAGACCA,185,ENSG00000004059,0.00465,3.92,109.0,0.01360,12.00,124.0,0.00498,2.13,79.6,0
3,ENST00000000233,244,AAGACCA,185,ENSG00000004059,0.00398,2.06,125.0,0.00830,5.01,130.0,0.00498,3.78,80.4,0
4,ENST00000000233,244,AAGACCA,185,ENSG00000004059,0.00664,2.92,120.0,0.00266,3.94,129.0,0.01300,7.15,82.2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11027101,ENST00000641834,1693,TTGACAT,52,ENSG00000167747,0.00418,7.49,108.0,0.00564,10.20,116.0,0.01000,2.01,76.4,0
11027102,ENST00000641834,1693,TTGACAT,52,ENSG00000167747,0.00664,1.91,109.0,0.00598,12.30,110.0,0.01760,2.61,74.6,0
11027103,ENST00000641834,1693,TTGACAT,52,ENSG00000167747,0.00721,4.58,105.0,0.00398,6.58,113.0,0.00316,2.28,85.3,0
11027104,ENST00000641834,1693,TTGACAT,52,ENSG00000167747,0.00266,2.33,109.0,0.00913,10.40,108.0,0.00664,4.44,76.8,0
11027105,ENST00000641834,1693,TTGACAT,52,ENSG00000167747,0.00564,3.13,110.0,0.00303,9.98,118.0,0.01930,1.79,76.2,0

In [6]:
df_pre.feature_eng()

,gene_id,transcript,position,nucleotides,reads_count,label,dwelling_time_-1_25,dwelling_time_-1_50,dwelling_time_-1_75,dwelling_time_-1_mean,...,std_+1_mean,std_+1_min,std_+1_max,mean_+1_25,mean_+1_50,mean_+1_75,mean_+1_mean,mean_+1_min,mean_+1_max,relative_position
0,ENSG00000000003,ENST00000373020,1006,TAGACCT,21,0,0.007650,0.009760,0.015100,0.010726,...,3.900476,1.100,9.19,75.800,77.10,77.800,76.857143,72.4,80.9,0.775510
1,ENSG00000000003,ENST00000373020,1013,AAAACTA,20,0,0.007965,0.009800,0.013175,0.011538,...,3.299000,1.550,6.33,92.125,93.25,94.975,93.765000,90.2,99.7,0.786499
2,ENSG00000000003,ENST00000373020,1149,GAAACAC,22,0,0.004917,0.007155,0.009473,0.008890,...,2.028182,1.220,4.30,89.450,90.65,92.600,90.777273,82.0,99.1,1.000000
3,ENSG00000000003,ENST00000373020,512,ATAACTC,20,0,0.004040,0.005990,0.008387,0.007247,...,1.588750,0.917,2.18,92.100,92.55,93.325,92.330000,83.5,94.5,0.000000
4,ENSG00000000003,ENST00000373020,689,TAAACAA,21,0,0.005310,0.007640,0.014300,0.009868,...,2.198571,1.350,4.15,88.500,89.60,90.600,89.385714,84.3,93.5,0.277865
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121833,ENSG00000284707,ENST00000641784,3122,CTGACCC,60,1,0.003980,0.005475,0.007947,0.007506,...,2.844667,1.240,5.64,79.675,81.15,82.725,80.915000,72.4,84.7,0.922372
121834,ENSG00000284707,ENST00000641784,3142,CTGACCC,61,0,0.005520,0.007640,0.011000,0.008712,...,3.218689,1.160,10.10,76.500,78.00,79.500,77.859016,71.2,83.5,0.933154
121835,ENSG00000284707,ENST00000641784,3224,GGGACTG,60,1,0.004650,0.006970,0.011150,0.008452,...,3.443833,1.200,8.95,88.675,91.45,93.325,91.126667,84.8,97.0,0.977358
121836,ENSG00000284707,ENST00000641784,3243,GGAACAA,64,0,0.004877,0.007350,0.010325,0.008700,...,2.203750,1.110,5.43,86.750,88.70,90.500,88.439062,80.3,97.4,0.987601
121837,ENSG00000284707,ENST00000641784,3266,CTAACTT,62,0,0.004000,0.005065,0.006970,0.005972,...,1.977742,0.930,4.36,91.550,92.65,93.200,92.453226,89.7,96.0,1.000000

In [7]:
df_all_features = df_pre.df

In [10]:
df_all_features[['dwelling_time_-1_25', 'dwelling_time_-1_50', 'dwelling_time_-1_75', 'dwelling_time_-1_mean', 'dwelling_time_-1_min', 'dwelling_time_-1_max', 'relative_position']].head(10)

,dwelling_time_-1_25,dwelling_time_-1_50,dwelling_time_-1_75,dwelling_time_-1_mean,dwelling_time_-1_min,dwelling_time_-1_max,relative_position
0,0.007650,0.009760,0.015100,0.010726,0.00299,0.0193,0.775510
1,0.007965,0.009800,0.013175,0.011538,0.00232,0.0362,0.786499
2,0.004917,0.007155,0.009473,0.008890,0.00266,0.0488,1.000000
3,0.004040,0.005990,0.008387,0.007247,0.00266,0.0169,0.000000
4,0.005310,0.007640,0.014300,0.009868,0.00232,0.0279,0.277865
5,0.005810,0.006310,0.007770,0.007456,0.00299,0.0196,0.488226
6,0.004897,0.006410,0.008913,0.007765,0.00266,0.0226,0.499215
7,0.004980,0.005980,0.007780,0.006785,0.00332,0.0181,0.529042
8,0.004163,0.007170,0.009545,0.007851,0.00232,0.0178,0.593407
9,0.006237,0.007750,0.012050,0.009428,0.00299,0.0229,0.665620

In [8]:
df_all_features.columns

Index(['gene_id', 'transcript', 'position', 'nucleotides', 'reads_count',
       'label', 'dwelling_time_-1_25', 'dwelling_time_-1_50',
       'dwelling_time_-1_75', 'dwelling_time_-1_mean', 'dwelling_time_-1_min',
       'dwelling_time_-1_max', 'std_-1_25', 'std_-1_50', 'std_-1_75',
       'std_-1_mean', 'std_-1_min', 'std_-1_max', 'mean_-1_25', 'mean_-1_50',
       'mean_-1_75', 'mean_-1_mean', 'mean_-1_min', 'mean_-1_max',
       'dwelling_time_0_25', 'dwelling_time_0_50', 'dwelling_time_0_75',
       'dwelling_time_0_mean', 'dwelling_time_0_min', 'dwelling_time_0_max',
       'std_0_25', 'std_0_50', 'std_0_75', 'std_0_mean', 'std_0_min',
       'std_0_max', 'mean_0_25', 'mean_0_50', 'mean_0_75', 'mean_0_mean',
       'mean_0_min', 'mean_0_max', 'dwelling_time_+1_25',
       'dwelling_time_+1_50', 'dwelling_time_+1_75', 'dwelling_time_+1_mean',
       'dwelling_time_+1_min', 'dwelling_time_+1_max', 'std_+1_25',
       'std_+1_50', 'std_+1_75', 'std_+1_mean', 'std_+1_min', 'std_+1_max',
       'mean_+1_25', 'mean_+1_50', 'mean_+1_75', 'mean_+1_mean', 'mean_+1_min',
       'mean_+1_max', 'relative_position'],
      dtype='object')

In [9]:
df_train, df_test, df_val, X_train, y_train, X_val, y_val, X_test, y_test, df_val_id = df_pre.split_stratified_into_train_val_test(random_state=42)

train target percentage: 0.043292122202922244
test target percentage: 0.0506553911205074
val target percentage: 0.052622910318702136
train data shape: (97870, 61)
validation data shape: (12143, 61)
test data shape: (11825, 61)

In [10]:
df_pre.X_train

,nucleotides,reads_count,dwelling_time_-1_25,dwelling_time_-1_50,dwelling_time_-1_75,dwelling_time_-1_mean,dwelling_time_-1_min,dwelling_time_-1_max,std_-1_25,std_-1_50,...,std_+1_mean,std_+1_min,std_+1_max,mean_+1_25,mean_+1_50,mean_+1_75,mean_+1_mean,mean_+1_min,mean_+1_max,relative_position
0,TAGACCT,21,0.007650,0.009760,0.015100,0.010726,0.00299,0.0193,2.8900,3.100,...,3.900476,1.100,9.19,75.800,77.10,77.800,76.857143,72.4,80.9,0.775510
1,AAAACTA,20,0.007965,0.009800,0.013175,0.011538,0.00232,0.0362,2.1925,2.460,...,3.299000,1.550,6.33,92.125,93.25,94.975,93.765000,90.2,99.7,0.786499
2,GAAACAC,22,0.004917,0.007155,0.009473,0.008890,0.00266,0.0488,2.2100,3.030,...,2.028182,1.220,4.30,89.450,90.65,92.600,90.777273,82.0,99.1,1.000000
3,ATAACTC,20,0.004040,0.005990,0.008387,0.007247,0.00266,0.0169,1.7400,2.325,...,1.588750,0.917,2.18,92.100,92.55,93.325,92.330000,83.5,94.5,0.000000
4,TAAACAA,21,0.005310,0.007640,0.014300,0.009868,0.00232,0.0279,1.7500,1.980,...,2.198571,1.350,4.15,88.500,89.60,90.600,89.385714,84.3,93.5,0.277865
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97865,CTGACCC,60,0.003980,0.005475,0.007947,0.007506,0.00232,0.0438,2.9425,3.270,...,2.844667,1.240,5.64,79.675,81.15,82.725,80.915000,72.4,84.7,0.922372
97866,CTGACCC,61,0.005520,0.007640,0.011000,0.008712,0.00232,0.0259,2.9700,3.470,...,3.218689,1.160,10.10,76.500,78.00,79.500,77.859016,71.2,83.5,0.933154
97867,GGGACTG,60,0.004650,0.006970,0.011150,0.008452,0.00232,0.0266,2.9300,3.700,...,3.443833,1.200,8.95,88.675,91.45,93.325,91.126667,84.8,97.0,0.977358
97868,GGAACAA,64,0.004877,0.007350,0.010325,0.008700,0.00204,0.0372,6.2825,7.680,...,2.203750,1.110,5.43,86.750,88.70,90.500,88.439062,80.3,97.4,0.987601
97869,CTAACTT,62,0.004000,0.005065,0.006970,0.005972,0.00232,0.0187,1.4625,1.760,...,1.977742,0.930,4.36,91.550,92.65,93.200,92.453226,89.7,96.0,1.000000

In [11]:
X_train_oversampled, y_train = df_pre.oversample_undersample()

In [12]:
X_train_enc, pipe = df_pre.encoding_train()

columns after preprocessing : ['reads_count', 'dwelling_time_-1_25', 'dwelling_time_-1_50', 'dwelling_time_-1_75', 'dwelling_time_-1_mean', 'dwelling_time_-1_min', 'dwelling_time_-1_max', 'std_-1_25', 'std_-1_50', 'std_-1_75', 'std_-1_mean', 'std_-1_min', 'std_-1_max', 'mean_-1_25', 'mean_-1_50', 'mean_-1_75', 'mean_-1_mean', 'mean_-1_min', 'mean_-1_max', 'dwelling_time_0_25', 'dwelling_time_0_50', 'dwelling_time_0_75', 'dwelling_time_0_mean', 'dwelling_time_0_min', 'dwelling_time_0_max', 'std_0_25', 'std_0_50', 'std_0_75', 'std_0_mean', 'std_0_min', 'std_0_max', 'mean_0_25', 'mean_0_50', 'mean_0_75', 'mean_0_mean', 'mean_0_min', 'mean_0_max', 'dwelling_time_+1_25', 'dwelling_time_+1_50', 'dwelling_time_+1_75', 'dwelling_time_+1_mean', 'dwelling_time_+1_min', 'dwelling_time_+1_max', 'std_+1_25', 'std_+1_50', 'std_+1_75', 'std_+1_mean', 'std_+1_min', 'std_+1_max', 'mean_+1_25', 'mean_+1_50', 'mean_+1_75', 'mean_+1_mean', 'mean_+1_min', 'mean_+1_max', 'relative_position', 'position_0_C', 'position_0_G', 'position_0_T', 'position_0_A', 'position_1_A', 'position_1_G', 'position_1_T', 'position_2_A', 'position_2_G', 'position_3_A', 'position_4_C', 'position_5_C', 'position_5_A', 'position_5_T', 'position_6_T', 'position_6_A', 'position_6_G', 'position_6_C']

In [13]:
X_train_enc

,reads_count,dwelling_time_-1_25,dwelling_time_-1_50,dwelling_time_-1_75,dwelling_time_-1_mean,dwelling_time_-1_min,dwelling_time_-1_max,std_-1_25,std_-1_50,std_-1_75,...,position_2_G,position_3_A,position_4_C,position_5_C,position_5_A,position_5_T,position_6_T,position_6_A,position_6_G,position_6_C
0,-0.429603,-0.097196,-0.491042,-0.681852,-0.757836,0.023085,-1.355167,-0.62558,-0.777883,-0.816721,...,0,1,1,1,0,0,1,0,0,0
1,-0.350251,-0.667241,-0.836892,-0.576006,-0.738994,0.023085,-0.981329,-0.912831,-0.745608,-0.591965,...,1,1,1,1,0,0,1,0,0,0
2,-0.494527,-1.646377,-1.552442,-1.727199,-1.942534,0.023085,-1.577449,-1.08984,-0.969047,-0.850329,...,0,1,1,0,1,0,0,1,0,0
3,-0.335823,-0.162025,-0.562597,-0.773584,-0.67433,1.436755,0.362466,-0.422175,-0.452655,-0.560457,...,1,1,1,0,1,0,1,0,0,0
4,-0.494527,-1.498836,-1.170815,-1.62841,-1.661636,-0.6732,-1.183403,-1.217162,-0.929325,-0.953254,...,0,1,1,0,0,1,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30401,0.219641,0.470179,0.772986,0.867393,0.872813,0.145475,0.404605,0.540573,0.480885,0.369271,...,1,1,1,0,0,1,0,0,0,1
30402,-0.487313,2.28499,1.788111,1.4412,1.842226,1.584522,-0.218663,0.821727,0.901437,0.788863,...,1,1,1,1,0,0,0,1,0,0
30403,-0.458458,1.235525,0.380691,0.320119,0.494436,1.955841,-0.194858,-0.721332,-0.8107,-0.864526,...,1,1,1,0,0,1,0,0,1,0
30404,0.024868,-0.458141,-0.088997,0.212745,0.014388,-1.212709,0.757649,2.440285,2.763417,3.023251,...,0,1,1,0,1,0,1,0,0,0
30405,-0.371892,1.857158,1.683864,1.534493,1.626573,0.260664,0.357242,0.139796,0.449005,0.365091,...,1,1,1,0,1,0,1,0,0,0

In [14]:
X_test_enc = df_pre.encoding_test_val(pipe = pipe)

In [15]:
X_val_enc = df_pre.encoding_test_val(pipe = pipe, test = False)

In [16]:
X_train_25 = X_train_enc.drop(columns=['dwelling_time_-1_50', 'dwelling_time_-1_75', 'dwelling_time_-1_mean', 'std_-1_50', 'std_-1_75', 'std_-1_mean', 'mean_-1_50', 'mean_-1_75', 'mean_-1_mean',
                                        'dwelling_time_0_50', 'dwelling_time_0_75', 'dwelling_time_0_mean', 'std_0_50', 'std_0_75', 'std_0_mean', 'mean_0_50', 'mean_0_75', 'mean_0_mean',
                                        'dwelling_time_+1_50', 'dwelling_time_+1_75', 'dwelling_time_+1_mean', 'std_+1_50', 'std_+1_75', 'std_+1_mean', 'mean_+1_50', 'mean_+1_75', 'mean_+1_mean'])

X_train_50 = X_train_enc.drop(columns=['dwelling_time_-1_25', 'dwelling_time_-1_75', 'dwelling_time_-1_mean', 'std_-1_25', 'std_-1_75', 'std_-1_mean', 'mean_-1_25', 'mean_-1_75', 'mean_-1_mean',
                                        'dwelling_time_0_25', 'dwelling_time_0_75', 'dwelling_time_0_mean', 'std_0_25', 'std_0_75', 'std_0_mean', 'mean_0_25', 'mean_0_75', 'mean_0_mean',
                                        'dwelling_time_+1_25', 'dwelling_time_+1_75', 'dwelling_time_+1_mean', 'std_+1_25', 'std_+1_75', 'std_+1_mean', 'mean_+1_25', 'mean_+1_75', 'mean_+1_mean'])

X_train_75 = X_train_enc.drop(columns=['dwelling_time_-1_25', 'dwelling_time_-1_50', 'dwelling_time_-1_mean', 'std_-1_25', 'std_-1_50', 'std_-1_mean', 'mean_-1_25', 'mean_-1_50', 'mean_-1_mean',
                                        'dwelling_time_0_25', 'dwelling_time_0_50', 'dwelling_time_0_mean', 'std_0_25', 'std_0_50', 'std_0_mean', 'mean_0_25', 'mean_0_50', 'mean_0_mean',
                                        'dwelling_time_+1_25', 'dwelling_time_+1_50', 'dwelling_time_+1_mean', 'std_+1_25', 'std_+1_50', 'std_+1_mean', 'mean_+1_25', 'mean_+1_50', 'mean_+1_mean'])

X_train_mean = X_train_enc.drop(columns=['dwelling_time_-1_25', 'dwelling_time_-1_50', 'dwelling_time_-1_75', 'std_-1_25', 'std_-1_50', 'std_-1_75', 'mean_-1_25', 'mean_-1_50', 'mean_-1_75',
                                        'dwelling_time_0_25', 'dwelling_time_0_50', 'dwelling_time_0_75', 'std_0_25', 'std_0_50', 'std_0_75', 'mean_0_25', 'mean_0_50', 'mean_0_75',
                                        'dwelling_time_+1_25', 'dwelling_time_+1_50', 'dwelling_time_+1_75', 'std_+1_25', 'std_+1_50', 'std_+1_75', 'mean_+1_25', 'mean_+1_50', 'mean_+1_75'])

In [17]:
X_train_25

,reads_count,dwelling_time_-1_25,dwelling_time_-1_min,dwelling_time_-1_max,std_-1_25,std_-1_min,std_-1_max,mean_-1_25,mean_-1_min,mean_-1_max,...,position_2_G,position_3_A,position_4_C,position_5_C,position_5_A,position_5_T,position_6_T,position_6_A,position_6_G,position_6_C
0,-0.429603,-0.097196,0.023085,-1.355167,-0.62558,-0.072106,-1.064669,-0.447642,-0.120673,-0.760289,...,0,1,1,1,0,0,1,0,0,0
1,-0.350251,-0.667241,0.023085,-0.981329,-0.912831,-0.773324,-0.164968,0.751178,0.833332,0.574992,...,1,1,1,1,0,0,1,0,0,0
2,-0.494527,-1.646377,0.023085,-1.577449,-1.08984,-0.692856,-0.644285,-2.098323,-1.628,-1.928661,...,0,1,1,0,1,0,0,1,0,0
3,-0.335823,-0.162025,1.436755,0.362466,-0.422175,0.100325,0.216128,-0.355425,-0.864796,-0.593379,...,1,1,1,0,1,0,1,0,0,0
4,-0.494527,-1.498836,-0.6732,-1.183403,-1.217162,-0.761828,-0.432128,-1.166933,-0.635835,-0.509924,...,0,1,1,0,0,1,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30401,0.219641,0.470179,0.145475,0.404605,0.540573,0.128775,0.149358,0.321559,0.388881,0.241172,...,1,1,1,0,0,1,0,0,0,1
30402,-0.487313,2.28499,1.584522,-0.218663,0.821727,1.902338,-0.215887,0.406041,0.821303,0.110728,...,1,1,1,1,0,0,0,1,0,0
30403,-0.458458,1.235525,1.955841,-0.194858,-0.721332,-0.138979,-1.068047,0.587279,1.143812,0.27303,...,1,1,1,0,0,1,0,0,1,0
30404,0.024868,-0.458141,-1.212709,0.757649,2.440285,1.477872,1.656524,1.304479,0.642531,1.447125,...,0,1,1,0,1,0,1,0,0,0
30405,-0.371892,1.857158,0.260664,0.357242,0.139796,-0.253473,-0.297607,0.447202,0.720258,0.12372,...,1,1,1,0,1,0,1,0,0,0

# Exporting Datasets

In [16]:
%cd data/preprocessed_data

c:\Users\lowmi\OneDrive\Desktop\Uni\DSA4262\DSA4262-ACMXZ\data\preprocessed_data

In [24]:
#into archive
df_all_features.to_parquet("archive/df_all_features.parquet") # df containing all features, before splitting/encoding
df_pre.df_test.to_parquet("archive/df_test.parquet") # df test containing all features and target, after splitting, before encoding
df_pre.df_train.to_parquet("archive/df_train.parquet") # df trin containing all features and target, after splitting, before encoding
df_pre.df_val.to_parquet("archive/df_val.parquet") # df val containing all features and target, after splitting, before encoding
df_pre.X_test.to_parquet("archive/X_test.parquet") # df test containing all features, after splitting, before encoding
df_pre.X_train.to_parquet("archive/X_train.parquet") # df train containing all features, after splitting, before encoding
df_pre.X_val.to_parquet("archive/X_val.parquet") # df val containing all features, after splitting, before encoding

#into test
df_pre.X_test_enc.to_parquet("test/X_test_enc.parquet") # df test containing all features, after encoding and oversampling
df_pre.y_test.to_parquet("test/y_test.parquet") # target test, after splitting, before encoding

#into training
X_train_25.to_parquet("training/X_train_25.parquet") # final df containing 25 percentile features for modelling
X_train_50.to_parquet("training/X_train_50.parquet") # final df containing 50 percentile features for modelling
X_train_75.to_parquet("training/X_train_75.parquet") # final df containing 75 percentile features for modelling
df_pre.X_train_enc.to_parquet("training/X_train_enc.parquet") # df train containing all features, after encoding and oversampling
X_train_mean.to_parquet("training/X_train_mean.parquet") # final df containing mean features for modelling
df_pre.y_train.to_parquet("training/y_train.parquet") # target train, after splitting, before encoding

#into validation
df_pre.X_val_enc.to_parquet("validation/X_val_enc.parquet") # df val containing all features, after encoding and oversampling
df_pre.y_val.to_parquet("validation/y_val.parquet") # target val, after splitting, before encoding
df_val_id.to_parquet("archive/df_val_id.parquet") # df val containing all features, identity cols and target, after splitting, before encoding

In [17]:
%cd ../raw_data

c:\Users\lowmi\OneDrive\Desktop\Uni\DSA4262\DSA4262-ACMXZ\data\raw_data

In [18]:
#encoding pipeline
filename = 'encoding_pipeline.pkl'
pickle.dump(pipe, open(filename, 'wb'))

# columns to map
filename = "columns.pkl"
pickle.dump(df_pre.columns_to_map, open(filename, 'wb'))

In [27]:
# df_all_features.to_parquet("df_all_features.parquet") # df containing all features, before splitting/encoding
# df_pre.df_train.to_parquet("df_train.parquet") # df trin containing all features and target, after splitting, before encoding
# df_pre.df_test.to_parquet("df_test.parquet") # df test containing all features and target, after splitting, before encoding
# df_pre.df_val.to_parquet("df_val.parquet") # df val containing all features and target, after splitting, before encoding
# df_pre.X_train.to_parquet("X_train.parquet") # df train containing all features, after splitting, before encoding
# df_pre.y_train.to_parquet("y_train.parquet") # target train, after splitting, before encoding
# df_pre.X_val.to_parquet("X_val.parquet") # df val containing all features, after splitting, before encoding
# df_pre.y_val.to_parquet("y_val.parquet") # target val, after splitting, before encoding
# df_pre.X_test.to_parquet("X_test.parquet") # df test containing all features, after splitting, before encoding
# df_pre.y_test.to_parquet("y_test.parquet") # target test, after splitting, before encoding
# df_val_id.to_parquet("df_val_id.parquet") # df val containing all features, identity cols and target, after splitting, before encoding
# df_pre.X_train_enc.to_parquet("X_train_enc.parquet") # df train containing all features, after encoding and oversampling
# df_pre.X_test_enc.to_parquet("X_test_enc.parquet") # df test containing all features, after encoding and oversampling
# df_pre.X_val_enc.to_parquet("X_val_enc.parquet") # df val containing all features, after encoding and oversampling
# X_train_25.to_parquet("X_train_25.parquet")  # final df containing 25 percentile features for modelling
# X_train_50.to_parquet("X_train_50.parquet") # final df containing 50 percentile features for modelling
# X_train_75.to_parquet("X_train_75.parquet") # final df containing 75 percentile features for modelling
# X_train_mean.to_parquet("X_train_mean.parquet") # final df containing mean features for modelling